# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.ImageField(default='static/cat.jpeg', upload_to='static/images'),
        ),
    ]
