# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_book_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='static/cat.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.ImageField(default='static/cat.jpeg', upload_to='images'),
        ),
    ]
